### ISSUE TITLE
Possible update to API v1.2

### ISSUE THREAD

**Issue by slagiewka** [gojuno/go-zooz#8]
Hello,

the PaymentsOS API has been updated over time from 1.0 to 1.2. Are you guys interested in having this library updated?

I have changes ready and I can prepare a PR if you will be willing to merge it in.

If you would still like to use the 1.0 version of the API, we could introduce releases and your projects would simply fetch the release using 1.0 connection.

Thoughts?

**Comment by hexdigest** [comment]
Hi, @slagiewka 

Thanks for pointing out to the issue. I would vote for releases.
@vpbarb what do you think?

**Comment by vpbarb** [comment]
It would be great to keep this package up to date. I will tag current version as 1.0 and feel free to make PR with 1.2 support. Thanks!
